--システム管理(Z) - ユーザマスタ(ZM001_USER)
CREATE TABLE ZM001_USER(
     USER_ID VARCHAR(50) NOT NULL,
     USER_DUE_DATE DATE DEFAULT '2099/12/31' NOT NULL,
     PASSWORD VARCHAR(100) NOT NULL,
     PASS_UPDATE DATE DEFAULT '2099/12/31' NOT NULL,
     LOGIN_MISS_TIMES SMALLINT DEFAULT 0 NOT NULL,
     LOCK_FLG BOOLEAN DEFAULT FALSE NOT NULL,
     ENABLED_FLG BOOLEAN DEFAULT TRUE NOT NULL,
     INSERT_USER VARCHAR(50) NOT NULL,
     INSERT_DATE TIMESTAMP NOT NULL,
     UPDATE_USER VARCHAR(50),
     UPDATE_DATE TIMESTAMP,
CONSTRAINT ZM001_USER_PK PRIMARY KEY (USER_ID)
);

COMMENT ON TABLE ZM001_USER is 'ユーザマスタ';
COMMENT ON COLUMN ZM001_USER.USER_ID is 'ユーザID';
COMMENT ON COLUMN ZM001_USER.USER_DUE_DATE is 'ユーザ有効期限';
COMMENT ON COLUMN ZM001_USER.PASSWORD is 'パスワード';
COMMENT ON COLUMN ZM001_USER.PASS_UPDATE is 'パスワード有効期限';
COMMENT ON COLUMN ZM001_USER.LOGIN_MISS_TIMES is 'ログイン失敗回数';
COMMENT ON COLUMN ZM001_USER.LOCK_FLG is 'ロック状態';
COMMENT ON COLUMN ZM001_USER.ENABLED_FLG is '有効フラグ';
COMMENT ON COLUMN ZM001_USER.INSERT_USER is '作成者';
COMMENT ON COLUMN ZM001_USER.INSERT_DATE is '作成日時';
COMMENT ON COLUMN ZM001_USER.UPDATE_USER is '更新者';
COMMENT ON COLUMN ZM001_USER.UPDATE_DATE is '更新日時';