--システム管理(Z) - ユーザロールマスタ(ZM003_USERROLE)
CREATE TABLE ZM003_USERROLE(
     USER_ID VARCHAR(50) NOT NULL,
     ROLE_ID VARCHAR(50) NOT NULL,
CONSTRAINT ZM003_USERROLE_PK PRIMARY KEY (USER_ID, ROLE_ID)
);

COMMENT ON TABLE ZM003_USERROLE is 'ユーザロールマスタ';
COMMENT ON COLUMN ZM003_USERROLE.USER_ID is 'ユーザID';
COMMENT ON COLUMN ZM003_USERROLE.ROLE_ID is 'ロールＩＤ';

--Foreign Key Constraints
ALTER TABLE ZM003_USERROLE ADD CONSTRAINT ZM003_USERROLE_FK1
      FOREIGN KEY (ROLE_ID)
      REFERENCES ZM002_ROLE (ROLE_ID);
ALTER TABLE ZM003_USERROLE ADD CONSTRAINT ZM003_USERROLE_FK2
      FOREIGN KEY (USER_ID)
      REFERENCES ZM001_USER (USER_ID);