--システム管理(Z) - ロールマスタ(ZM002_ROLE)
CREATE TABLE ZM002_ROLE(
     ROLE_ID VARCHAR(50) NOT NULL,
     ROLE_NAME VARCHAR(50),
     BIKO VARCHAR(50),
     INSERT_USER VARCHAR(50) NOT NULL,
     INSERT_DATE TIMESTAMP NOT NULL,
     UPDATE_USER VARCHAR(50),
     UPDATE_DATE TIMESTAMP,
CONSTRAINT ZM002_ROLE_PK PRIMARY KEY (ROLE_ID)
);

COMMENT ON TABLE ZM002_ROLE is 'ロールマスタ';
COMMENT ON COLUMN ZM002_ROLE.ROLE_ID is 'ロールＩＤ';
COMMENT ON COLUMN ZM002_ROLE.ROLE_NAME is 'ロール名';
COMMENT ON COLUMN ZM002_ROLE.BIKO is '備考';
COMMENT ON COLUMN ZM002_ROLE.INSERT_USER is '作成者';
COMMENT ON COLUMN ZM002_ROLE.INSERT_DATE is '作成日時';
COMMENT ON COLUMN ZM002_ROLE.UPDATE_USER is '更新者';
COMMENT ON COLUMN ZM002_ROLE.UPDATE_DATE is '更新日時';