--システム管理(Z) - 従業員マスタ(ZM004_EMP)
CREATE TABLE ZM004_EMP(
     EMP_ID VARCHAR(50) NOT NULL,
     EMP_NAME VARCHAR(50),
     MAILADDRESS VARCHAR(50),
     BIRTHDAY DATE NOT NULL,
     MARRIAGE_FLG BOOLEAN DEFAULT FALSE NOT NULL,
     USER_ID VARCHAR(50),
     INSERT_USER VARCHAR(50) NOT NULL,
     INSERT_DATE TIMESTAMP NOT NULL,
     UPDATE_USER VARCHAR(50),
     UPDATE_DATE TIMESTAMP,
CONSTRAINT ZM004_EMP_PK PRIMARY KEY (EMP_ID)
);

COMMENT ON TABLE ZM004_EMP is '従業員マスタ';
COMMENT ON COLUMN ZM004_EMP.EMP_ID is '従業員ＩＤ';
COMMENT ON COLUMN ZM004_EMP.EMP_NAME is '従業員名';
COMMENT ON COLUMN ZM004_EMP.MAILADDRESS is 'メールアドレス';
COMMENT ON COLUMN ZM004_EMP.BIRTHDAY is '生年月日';
COMMENT ON COLUMN ZM004_EMP.MARRIAGE_FLG is '結婚フラグ';
COMMENT ON COLUMN ZM004_EMP.USER_ID is 'ユーザID';
COMMENT ON COLUMN ZM004_EMP.INSERT_USER is '作成者';
COMMENT ON COLUMN ZM004_EMP.INSERT_DATE is '作成日時';
COMMENT ON COLUMN ZM004_EMP.UPDATE_USER is '更新者';
COMMENT ON COLUMN ZM004_EMP.UPDATE_DATE is '更新日時';


--Foreign Key Constraints
ALTER TABLE ZM004_EMP ADD CONSTRAINT ZM004_EMP_FK1
      FOREIGN KEY (USER_ID)
      REFERENCES ZM001_USER (USER_ID);