--システム管理(Z) - ロール名(ZM500_ROLE_NAME_LIST)
CREATE TABLE ZM500_ROLE_NAME_LIST(
     ROLE_NAME VARCHAR(50) NOT NULL,
     ENABLED_FLG BOOLEAN DEFAULT TRUE NOT NULL,
CONSTRAINT ZM500_ROLE_NAME_LIST_PK PRIMARY KEY (ROLE_NAME)
);

COMMENT ON TABLE ZM500_ROLE_NAME_LIST is 'ロール名';
COMMENT ON COLUMN ZM500_ROLE_NAME_LIST.ROLE_NAME is 'ロール名';
COMMENT ON COLUMN ZM500_ROLE_NAME_LIST.ENABLED_FLG is '有効フラグ';