--システム管理(Z) - 環境マスタ(ZM999_ENV)
CREATE TABLE ZM999_ENV(
     ENV_ID VARCHAR(50) NOT NULL,
     ENV_KBN VARCHAR(20),
     ENV_NUM SMALLINT DEFAULT 0 NOT NULL,
     ENV_TXT VARCHAR(100) NOT NULL,
     BIKO VARCHAR(100),
     INSERT_USER VARCHAR(50) NOT NULL,
     INSERT_DATE TIMESTAMP NOT NULL,
     UPDATE_USER VARCHAR(50),
     UPDATE_DATE TIMESTAMP,
CONSTRAINT ZM999_ENV_PK PRIMARY KEY (ENV_ID)
);

COMMENT ON TABLE ZM999_ENV is '環境マスタ';
COMMENT ON COLUMN ZM999_ENV.ENV_ID is '環境ＩＤ';
COMMENT ON COLUMN ZM999_ENV.ENV_KBN is '環境区分';
COMMENT ON COLUMN ZM999_ENV.ENV_NUM is '環境連番';
COMMENT ON COLUMN ZM999_ENV.ENV_TXT is '環境値';
COMMENT ON COLUMN ZM999_ENV.BIKO is '備考';
COMMENT ON COLUMN ZM999_ENV.INSERT_USER is '作成者';
COMMENT ON COLUMN ZM999_ENV.INSERT_DATE is '作成日時';
COMMENT ON COLUMN ZM999_ENV.UPDATE_USER is '更新者';
COMMENT ON COLUMN ZM999_ENV.UPDATE_DATE is '更新日時';