--システム管理(Z) - パスワード再発行情報(ZT001_PWREISSUEINFO)
CREATE TABLE ZT001_PWREISSUEINFO(
     TOKEN VARCHAR(128) NOT NULL,
     USER_ID VARCHAR(50) NOT NULL,
     SECRET VARCHAR(88) NOT NULL,
     EXPIRYDATE TIMESTAMP NOT NULL,
CONSTRAINT ZT001_PWREISSUEINFO_PK PRIMARY KEY (TOKEN)
);

COMMENT ON TABLE ZT001_PWREISSUEINFO is 'パスワード再発行情報';
COMMENT ON COLUMN ZT001_PWREISSUEINFO.TOKEN is 'トークン';
COMMENT ON COLUMN ZT001_PWREISSUEINFO.USER_ID is 'ユーザID';
COMMENT ON COLUMN ZT001_PWREISSUEINFO.SECRET is '秘密情報';
COMMENT ON COLUMN ZT001_PWREISSUEINFO.EXPIRYDATE is '認証情報有効期限';


--Foreign Key Constraints
ALTER TABLE ZT001_PWREISSUEINFO ADD CONSTRAINT ZT001_PWREISSUEINFO_FK1
      FOREIGN KEY (USER_ID)
      REFERENCES ZM001_USER (USER_ID);